[package]
name = "orpc-net"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ORPC network migration boundary."

[dependencies]
curvine-io = { workspace = true }
orpc-error = { workspace = true }
orpc-runtime = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
