[package]
name = "curvine-mds"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
curvine-config = { workspace = true }
curvine-core-error = { workspace = true }
curvine-metrics = { workspace = true }
curvine-runtime = { workspace = true }
async-trait = { workspace = true }
fastrand = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
